services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # -----------------------------------------------------------
  # 🔹 Alle Bundle-Klassen automatisch laden
  # -----------------------------------------------------------
  PbdKn\ContaoEllipseBundle\:
    resource: '../../*'
    exclude:
      - '../../Resources/contao'   # DCA, Templates etc.
      - '../../Resources/config'   # keine Rekursion


  # -----------------------------------------------------------
  # 🔹 Services explizit freigeben (z. B. für Controller)
  # -----------------------------------------------------------
  PbdKn\ContaoEllipseBundle\Service\EllipseParameterHelper:
    public: true

  PbdKn\ContaoEllipseBundle\Service\LoggerService:
    public: true
